name: .NET CI
on:
  push: { branches: [ "**" ] }
  pull_request: { branches: [ "**" ] }
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }
      - run: dotnet restore TaskManager.sln
      - run: dotnet build TaskManager.sln --configuration Release --no-restore
      - run: dotnet test TaskManager.Tests/TaskManager.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
